// <auto-generated />
using System;
using FoodDelivery.DAL.EFCore.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodDelivery.DAL.EFCore.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddressEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "New York",
                            Number = "3818",
                            PostalCode = "10016",
                            Street = "My Drive"
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.FeedbackEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MealId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("FeedbackEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Too bad... Didn't like it at all.",
                            MealId = 1,
                            Rating = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "Eh...",
                            MealId = 2,
                            Rating = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Not great, not terrible.",
                            MealId = 3,
                            Rating = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            Description = "Liked it a lot!!",
                            MealId = 4,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            Description = "Awesome! Best thing I ever eaten!",
                            MealId = 5,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            Description = "Awesome! Best thing I ever eaten!",
                            MealId = 6,
                            Rating = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            Description = "Liked it a lot!!",
                            MealId = 7,
                            Rating = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Not great, not terrible.",
                            MealId = 8,
                            Rating = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            Description = "Eh...",
                            MealId = 9,
                            Rating = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            Description = "Too bad... Didn't like it at all.",
                            MealId = 10,
                            Rating = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 11,
                            Description = "Really bad place.",
                            Rating = 1,
                            RestaurantId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 12,
                            Description = "Won't come again...",
                            Rating = 2,
                            RestaurantId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 13,
                            Description = "Could have been better.",
                            Rating = 3,
                            RestaurantId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 14,
                            Description = "Great place!",
                            Rating = 4,
                            RestaurantId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 15,
                            Description = "My favorite place! I highly recommend!",
                            Rating = 5,
                            RestaurantId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 16,
                            Description = "My favorite place! I highly recommend!",
                            Rating = 5,
                            RestaurantId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 17,
                            Description = "Great place!",
                            Rating = 4,
                            RestaurantId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 18,
                            Description = "Could have been better.",
                            Rating = 3,
                            RestaurantId = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 19,
                            Description = "Won't come again...",
                            Rating = 2,
                            RestaurantId = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 20,
                            Description = "Really bad place.",
                            Rating = 1,
                            RestaurantId = 10,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.MealEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RestaurantId");

                    b.ToTable("MealEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fresh egg pasta in a sauce made from fresh broccoli and smoked pancetta",
                            MealType = "Pasta",
                            Name = "Broccoli and pancetta fusilli",
                            Price = 10.5,
                            RestaurantId = 1
                        },
                        new
                        {
                            Id = 2,
                            Description = "A warm bagel filled with steak and parmesan",
                            MealType = "Steak",
                            Name = "Steak and parmesan bagel",
                            Price = 15.199999999999999,
                            RestaurantId = 2
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh egg tubular pasta in a sauce made from tuna and tangy lemon",
                            MealType = "Pasta",
                            Name = "Tuna and lemon penne",
                            Price = 8.5999999999999996,
                            RestaurantId = 3
                        },
                        new
                        {
                            Id = 4,
                            Description = "Succulent burger made from chunky sausage and spicy chilli, served in a roll",
                            MealType = "Burger",
                            Name = "Sausage and chilli burger",
                            Price = 16.5,
                            RestaurantId = 4
                        },
                        new
                        {
                            Id = 5,
                            Description = "A warm bagel filled with grouse and romaine lettuce",
                            MealType = "Bagel",
                            Name = "Grouse and lettuce bagel",
                            Price = 5.0999999999999996,
                            RestaurantId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Sizzling sausages made from smoked tofu and pattypan squash, served in a roll",
                            MealType = "Vegan",
                            Name = "Tofu and squash sausages",
                            Price = 7.0999999999999996,
                            RestaurantId = 6
                        },
                        new
                        {
                            Id = 7,
                            Description = "Fresh strawberries and sweet pepper combined into smooth soup",
                            MealType = "Soup",
                            Name = "Strawberry and pepper soup",
                            Price = 8.0,
                            RestaurantId = 7
                        },
                        new
                        {
                            Id = 8,
                            Description = "Sole and fresh durian served on a bed of lettuce",
                            MealType = "Salad",
                            Name = "Sole and durian salad",
                            Price = 10.5,
                            RestaurantId = 8
                        },
                        new
                        {
                            Id = 9,
                            Description = "A mouth-watering pasta salad served with garlic dressing",
                            MealType = "Pasta salad",
                            Name = "Pasta salad with garlic dressing",
                            Price = 11.300000000000001,
                            RestaurantId = 9
                        },
                        new
                        {
                            Id = 10,
                            Description = "Fresh egg pasta in a sauce made from green pesto and baby spinach",
                            MealType = "Pasta",
                            Name = "Pesto and spinach pasta",
                            Price = 8.0,
                            RestaurantId = 10
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.OrderEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<int?>("RestaurantId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("RestaurantId");

                    b.HasIndex("UserId");

                    b.ToTable("OrderEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            PaymentType = 0,
                            RestaurantId = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 1,
                            PaymentType = 0,
                            RestaurantId = 2,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 1,
                            PaymentType = 0,
                            RestaurantId = 3,
                            UserId = 2
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            PaymentType = 0,
                            RestaurantId = 4,
                            UserId = 2
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 1,
                            PaymentType = 0,
                            RestaurantId = 5,
                            UserId = 2
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 1,
                            PaymentType = 1,
                            RestaurantId = 6,
                            UserId = 2
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 1,
                            PaymentType = 1,
                            RestaurantId = 7,
                            UserId = 2
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 1,
                            PaymentType = 1,
                            RestaurantId = 8,
                            UserId = 2
                        },
                        new
                        {
                            Id = 9,
                            AddressId = 1,
                            PaymentType = 1,
                            RestaurantId = 9,
                            UserId = 2
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 1,
                            PaymentType = 2,
                            RestaurantId = 10,
                            UserId = 2
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.OrderItemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int?>("MealId")
                        .HasColumnType("int");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("UnitPrice")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MealId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItemEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 2,
                            MealId = 1,
                            OrderId = 1,
                            UnitPrice = 10.5
                        },
                        new
                        {
                            Id = 2,
                            Amount = 3,
                            MealId = 3,
                            OrderId = 1,
                            UnitPrice = 8.5999999999999996
                        },
                        new
                        {
                            Id = 3,
                            Amount = 1,
                            MealId = 2,
                            OrderId = 2,
                            UnitPrice = 15.199999999999999
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1,
                            MealId = 3,
                            OrderId = 2,
                            UnitPrice = 8.5999999999999996
                        },
                        new
                        {
                            Id = 5,
                            Amount = 2,
                            MealId = 4,
                            OrderId = 2,
                            UnitPrice = 16.5
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1,
                            MealId = 1,
                            OrderId = 3,
                            UnitPrice = 10.5
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1,
                            MealId = 10,
                            OrderId = 3,
                            UnitPrice = 8.0
                        },
                        new
                        {
                            Id = 8,
                            Amount = 5,
                            MealId = 7,
                            OrderId = 4,
                            UnitPrice = 8.0
                        },
                        new
                        {
                            Id = 9,
                            Amount = 2,
                            MealId = 5,
                            OrderId = 5,
                            UnitPrice = 5.0999999999999996
                        },
                        new
                        {
                            Id = 10,
                            Amount = 4,
                            MealId = 9,
                            OrderId = 6,
                            UnitPrice = 11.300000000000001
                        },
                        new
                        {
                            Id = 11,
                            Amount = 1,
                            MealId = 7,
                            OrderId = 7,
                            UnitPrice = 8.0
                        },
                        new
                        {
                            Id = 12,
                            Amount = 4,
                            MealId = 8,
                            OrderId = 8,
                            UnitPrice = 10.5
                        },
                        new
                        {
                            Id = 13,
                            Amount = 3,
                            MealId = 9,
                            OrderId = 9,
                            UnitPrice = 11.300000000000001
                        },
                        new
                        {
                            Id = 14,
                            Amount = 1,
                            MealId = 6,
                            OrderId = 9,
                            UnitPrice = 7.0999999999999996
                        },
                        new
                        {
                            Id = 15,
                            Amount = 1,
                            MealId = 1,
                            OrderId = 10,
                            UnitPrice = 10.5
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.RestaurantEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RestaurantEntity");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Disabled = false,
                            Name = "The Private Port"
                        },
                        new
                        {
                            Id = 2,
                            Disabled = false,
                            Name = "The Sailing Stranger"
                        },
                        new
                        {
                            Id = 3,
                            Disabled = false,
                            Name = "The Juniper Angel"
                        },
                        new
                        {
                            Id = 4,
                            Disabled = false,
                            Name = "The Mountain Courtyard"
                        },
                        new
                        {
                            Id = 5,
                            Disabled = false,
                            Name = "The Mountain Lantern"
                        },
                        new
                        {
                            Id = 6,
                            Disabled = false,
                            Name = "Indigo"
                        },
                        new
                        {
                            Id = 7,
                            Disabled = false,
                            Name = "The Peacock"
                        },
                        new
                        {
                            Id = 8,
                            Disabled = false,
                            Name = "Sapphire"
                        },
                        new
                        {
                            Id = 9,
                            Disabled = false,
                            Name = "The Nightingale"
                        },
                        new
                        {
                            Id = 10,
                            Disabled = false,
                            Name = "Mumbles"
                        });
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int?>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "a87273f2-051c-4496-970c-75e4bb86be41",
                            Email = "admin@admin.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Admin",
                            NormalizedEmail = "ADMIN@ADMIN.COM",
                            NormalizedUserName = "ADMIN@ADMIN.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJeKJ8P325zcvS4xXjJeEWPBkV9rWizpodq0WNcVz8WPdSeDxF84cXyl+XOByB4pMw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8F180DE7183C48DFA0727158294BC650",
                            Surname = "Admin",
                            TwoFactorEnabled = false,
                            UserName = "admin@admin.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            AddressId = 1,
                            ConcurrencyStamp = "61dcdd9b-7be9-4bd8-a2e3-ce1327de6653",
                            Email = "marek@example.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            Name = "Marek",
                            NormalizedEmail = "MAREK@EXAMPLE.COM",
                            NormalizedUserName = "MAREK@EXAMPLE.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEIv+TtgUg8LTFCw6sNIqVlSv80ZOm9YVH54fvaiF1RKHKWr/Vk4ePCkwJuntIaLgww==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0B80BDB69C1A48EEB3D7945C53004B38",
                            Surname = "Macho",
                            TwoFactorEnabled = false,
                            UserName = "marek@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "03f744b6-1e51-4ce6-abca-fa8faadad503",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "c28976a9-6c39-4691-a0dc-d08742b67089",
                            Name = "Customer",
                            NormalizedName = "CUSTOMER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.FeedbackEntity", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.MealEntity", "Meal")
                        .WithMany("Feedbacks")
                        .HasForeignKey("MealId");

                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.RestaurantEntity", "Restaurant")
                        .WithMany("Feedbacks")
                        .HasForeignKey("RestaurantId");

                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Meal");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.MealEntity", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.RestaurantEntity", "Restaurant")
                        .WithMany("Meals")
                        .HasForeignKey("RestaurantId");

                    b.Navigation("Restaurant");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.OrderEntity", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.AddressEntity", "Address")
                        .WithMany("Orders")
                        .HasForeignKey("AddressId");

                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.RestaurantEntity", "Restaurant")
                        .WithMany()
                        .HasForeignKey("RestaurantId");

                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId");

                    b.Navigation("Address");

                    b.Navigation("Restaurant");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.OrderItemEntity", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.MealEntity", "Meal")
                        .WithMany("OrderItems")
                        .HasForeignKey("MealId");

                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.OrderEntity", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId");

                    b.Navigation("Meal");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.UserEntity", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<int>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("FoodDelivery.DAL.EFCore.Entities.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.AddressEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.MealEntity", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.OrderEntity", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.RestaurantEntity", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Meals");
                });

            modelBuilder.Entity("FoodDelivery.DAL.EFCore.Entities.UserEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
